### PR TITLE
fix: Add missing full stops

### PR DESCRIPTION
**Pull request by matthew-andrews**

### CODE REVIEW

**Comment by bjfletcher** [comment]
Hmm... pass. Maybe ask one of the UX people? Personally I prefer it without the fullstops at the end. Actually, a tad too many fullstops I think...

But that's me. :)  You know best, MA!

**Comment by matthew-andrews** [comment]
It's consistent with itself now :)

**Comment by bjfletcher** [comment]
Flip a coin? Actually, roll a dice... 1-5, this goes in. 6, show it to UX people and ask them for their verdict... they sit behind me. :)

**Comment by matthew-andrews** [comment]
i asked in slack https://financialtimes.slack.com/archives/next-designux/p1478106379000258

**Comment by commuterjoy** [comment]
This ticket needs it's own Trello board. Can we get a working group together to discuss?

**Comment by andygout** [comment]
If we are using other punctuation in other parts of the sentences (commas appear in some), then that to me would warrant the inclusion of full stops, else those commas are seemingly without context. Not sure if there is a hard and fast rule about it, though.

**Pull request merged**
