### PR TITLE
Add visually-hidden helper

### PR DESCRIPTION
**Pull request by phamann**
ronseal

### CODE REVIEW

**Comment by matthew-andrews** [comment]
adding Sass that an app isn't using …… what's the thinking here ?

**Comment by phamann** [comment]
@matthew-andrews https://github.com/Financial-Times/next-express/pull/186

**Comment by matthew-andrews** [comment]
or is it pulled into a component?  kind of uncomfortable……  this could easily be deleted (because it _looks_ unused) which would break MyFT…… seems like a lot of effort to go to just to avoid having a single line of sass added myft component (`@include nextSassSetupVisuallyHidden`)

**Comment by matthew-andrews** [comment]
https://github.com/Financial-Times/next-express/pull/186#issuecomment-118366599

**Comment by phamann** [comment]
@matthew-andrews see my comment above re global skip links inside next-express template and my entire thread on Slack. This being my main argument for having global utility helpers.

**Pull request closed without merging**
